# These default parameters can be overridden in config.json
import os
script_dir = os.path.dirname(__file__)

parameters = {
    # IMPORTANT:
    # the convergence.py depends on the PlateTectonicTools,
    # you need to tell the script where to find it
    # The PlateTectonicTools repository https://github.com/EarthByte/PlateTectonicTools.git is a submodule now
    # run the following command after you have cloned this spatio-temporal exploration repository.
    # git submodule update --init --recursive
    'plate_tectonic_tools_path' : script_dir + './../PlateTectonicTools/ptt/',
 
    'case_name' : 'default-test-case-name',
    
    'time' : {
        'start' : 0,
        'end'   : 230,
        'step'  : 1
    },
    
    # the file which contains the seed points.
    # coregistration input file
    'coreg_input_files' : ['samples.csv',  'random_samples.csv',  'mineral_occurrences.csv'],
    
    # folder contains the coregistration input files.
    'coreg_input_dir' : 'coreg_input',

    # folder contains the coregistration output files.
    'coreg_output_dir' : 'coreg_output',

    # folder contains the machine learning input files.
    'ml_input_dir' : 'ml_input',

    # folder contains the machine learning output files.
    'ml_output_dir' : 'ml_output',

    'machine_learning_engine' : 'RFC', # 'RFC' random forest; 'SVC' support vector classification
   
    'feature_names' : ['dist_nearest_edge', 'trench_abs_ortho', 'conv_ortho', 'conv_paral'],
    
    # the region of interest parameters are used in coregistration.py
    # given a seed point, the coregistration code looks for the nearest geomery within region[0] first
    # if not found, continue to search in region[1], region[2], etc
    # if still not found after having tried all regions, give up
    # the distance is in degrees. 
    'regions' : [5, 10, 15, 20],
    'region_of_interest_vertices' : script_dir + '/../GIS/PNG_Papua_Dissolved_CH_Points.csv',
    'region_of_interest_polygon' : script_dir + '/../GIS/PNG_Papua_Dissolved.shp',
    'deposit_path' : script_dir + '/../GIS/min_occ_holm_porphyry.shp',
    
    'rotation_files' : script_dir+'/../Muller_2016/Global_EarthByte_230-0Ma_GK07_AREPS.rot',
    'topology_files' : script_dir+'/../Muller_2016/Global_EarthByte_230-0Ma_GK07_AREPS_PlateBoundaries.gpml.gz',
    'static_polygons_file' : script_dir+'/../Muller_2016/Global_EarthByte_GPlates_PresentDay_StaticPlatePolygons_2015_v1.shp',
    'coastlines' : script_dir+'/../Muller_2016/Global_EarthByte_230-0Ma_GK07_AREPS_Coastlines.gpmlz',
    'agegrid_url' : '',
    
    # the following two parameters are used by subduction_convergence
    # see https://github.com/EarthByte/PlateTectonicTools/blob/master/ptt/subduction_convergence.py
    'threshold_sampling_distance_degrees' : 0.2,
    'velocity_delta_time' : 1,
    
    # a list of file paths from which the coregistration scripts query data
    'vector_files' : [
        '{conv_dir}subStats_{time:.2f}.csv', # can be generated by convergence.py
        # './convergence_data/subStats_{time:.2f}.csv',
        # more files below
    ],
    
    'anchor_plate_id' : 0, # see https://www.gplates.org/user-manual/MoreReconstructions.html
    
    # a list of grid files from which the coregistration scripts query data
    'grid_files' : [
        # ['../Muller_2016/Muller_etal_2016_AREPS_v1.17_netCDF/Muller_etal_2016_AREPS_v1.17_AgeGrid-{time:d}.nc', 'seafloor_age'],
        # ['../Muller_2016/carbonate_sediment_thickness_grids/compacted_sediment_thickness_0.5_{time:d}.nc', 'carbonate_sediment_thickness'],
        # ['../Muller_2016/sediment_thickness_grids/sed_thick_0.2d_{time:d}.nc', 'total_sediment_thick'],
        # ['../Muller_2016/oceanic_crustal_CO2_grids/co2_percent_{time:d}.nc', 'ocean_crust_carb_percent']
    ],
    
    'convergence_data_filename_prefix' : 'subStats',
    'convergence_data_filename_ext' : 'csv',
    'convergence_data_dir' : './convergence_data/',

    'overwrite_existing_convergence_data' : False, # if True, always generate the new convergence data
    'map_extent' : [128, 152, -12, 2],
    'topo_grid' : '../GIS/topo15_3600x1800.nc',
    'terranes' : ''
}
