# These default parameters can be overridden in config.json
# import os
# script_dir = os.path.dirname(__file__)

parameters = {
    # IMPORTANT:
    # the convergence.py depends on the PlateTectonicTools,
    # you need to tell the script where to find it
    # The PlateTectonicTools repository https://github.com/EarthByte/PlateTectonicTools.git is a submodule now
    # run the following command after you have cloned this spatio-temporal exploration repository.
    # git submodule update --init --recursive

    'agegrid_dir': '../Muller_2019/Muller_etal_2019_Tectonics_v2.0_netCDF/',
    'agegrid_url' : 'https://www.earthbyte.org/webdav/ftp/Data_Collections/Muller_etal_2019_Tectonics/Muller_etal_2019_Agegrids/Muller_etal_2019_Tectonics_v2.0_netCDF/Muller_etal_2019_Tectonics_v2.0_AgeGrid-{}.nc',
    
    'coastlines_file' : '../Muller_2019/coastlines/Global_coastlines_2019_v1_low_res.shp',
    'rotation_dir' : '../Muller_2019/rotation',
    'static_polygons_file' : '../Muller_2019/static_polygons/Global_EarthByte_GPlates_PresentDay_StaticPlatePolygons_2019_v1.shp',
    'topology_dir' : '../Muller_2019/topology',

    'anchor_plate_id' : 0, # see https://www.gplates.org/user-manual/MoreReconstructions.html
    
    'case_name' : 'default-test-case-name',
    
    'convergence_data_dir' : './convergence_kinematic_features/',
    'convergence_data_filename_prefix' : 'features',
    'convergence_data_filename_ext' : 'csv',

    # folder contains the coregistration input files.
    'coreg_input_dir' : './coreg_input/',

    # the file which contains the seed points.
    # coregistration input file
    'coreg_input_files' : ['mineral_occurrences.csv', 'random_samples.csv', 'target_points'],
    # folder contains the coregistration output files.
    'coreg_output_dir' : './coreg_output/',

    # a list of grid files from which the coregistration scripts query data
    'grid_files' : [
        ['../Muller_2019/Muller_etal_2019_Tectonics_v2.0_netCDF/Muller_etal_2019_Tectonics_v2.0_AgeGrid-{time:d}.nc', 'seafloor_age_ma'],
        ['../Muller_2019/compacted_carbonate_sediment_thickness/compacted_sediment_thickness_0.5_{time:d}.nc', 'carbonate_sediment_thickness_m'],
        ['../Muller_2019/compacted_sediment_thickness/sed_thick_0.1d_{time:d}.nc', 'total_sediment_thick_m'],
        ['../Muller_2019/ocean_crust_CO2_mean/ocean_crust_carb_percent_{time:d}.nc', 'ocean_crust_carb_percent']
    ],

    'target_extent_file' : '../GIS/target_extent_v1.3.shp',
    
    # 'min_occ_file' : '../GIS/min_occ_holm_porphyry.shp',
    'min_occ_file' : '../GIS/min_occ_holm.shp',

    # folder contains the machine learning input files.
    'ml_input_dir' : './ml_input/',

    # folder contains the machine learning output files.
    'ml_output_dir' : './ml_output/',

    'overwrite_existing_convergence_data' : False, # if True, always generate the new convergence data

    'plate_tectonic_tools_path' : '../PlateTectonicTools/ptt/',

    # the region of interest parameters are used in coregistration.py
    # given a seed point, the coregistration code looks for the nearest geomery within region[0] first
    # if not found, continue to search in region[1], region[2], etc
    # if still not found after having tried all regions, give up
    # the distance is in degrees.
    'region_of_interest_vertices' : '../GIS/PNG_Papua_Dissolved_CH_Points.csv',
    'region_of_interest_polygon' : '../GIS/PNG_Papua_Dissolved.shp',
    'regions' : [5, 10, 15, 20],

    'selected_features' : ['distance_deg', 'conv_rate_cm_yr', 'conv_angle_deg', 'trench_abs_rate_cm_yr',
                       'trench_abs_angle_deg', 'arc_len_deg', 'trench_norm_deg', 'dist_nearest_edge_deg',
                       'dist_from_start_deg', 'conv_ortho_cm_yr', 'conv_paral_cm_yr', 'trench_abs_ortho_cm_yr',
                       'trench_abs_paral_cm_yr', 'subducting_abs_rate_cm_yr', 'subducting_abs_angle_deg',
                       'subducting_abs_ortho_cm_yr', 'subducting_abs_paral_cm_yr', 'seafloor_age_ma',
                       'subduction_volume_km3_yr', 'carbonate_sediment_thickness_m',
                       'total_sediment_thick_m', 'ocean_crust_carb_percent'],

    'terranes' : '',

    # the following two parameters are used by subduction_convergence
    # see https://github.com/EarthByte/PlateTectonicTools/blob/master/ptt/subduction_convergence.py
    'threshold_sampling_distance_degrees' : 0.2,
    'velocity_delta_time' : 1,

    'time' : {
        'start' : 0,
        'end'   : 45, # 230 for Muller 2016
        'step'  : 1
    },

    'topo_grid_file' : '../GIS/topo15_3600x1800.nc',
    
    # a list of file paths from which the coregistration scripts query data
    'vector_files' : [
        '{conv_dir}features_{time:.2f}.csv', # can be generated by convergence.py
        # './convergence_data/features_{time:.2f}.csv',
        ]
    }
